package org.example.model;

import java.util.List;
import java.util.Map;

public class Piece {
    public static Map<Short, String> name = Map.of(
            (short) 1, "pawn",
            (short) 2, "knight",
            (short) 3, "bishop",
            (short) 4, "rock",
            (short) 5, "quinn",
            (short) 6, "king");

    public static Map<Short, List<Move>> moves = Map.of(
            (short) 1, List.of(
                    new Move((short) 0, (short) 2),
                    new Move((short) 0, (short) 1),
                    new Move((short) 1, (short) 1),
                    new Move((short) -1, (short) 1)),
            (short) 2, List.of(
                    new Move((short) -1, (short) 2),
                    new Move((short) 1, (short) 2),
                    new Move((short) 2, (short) 1),
                    new Move((short) 2, (short) -1),
                    new Move((short) 1, (short) -2),
                    new Move((short) -1, (short) -2),
                    new Move((short) -2, (short) -1),
                    new Move((short) -2, (short) 1)),
            (short) 3, List.of(
                    new Move((short) 1, (short) 1),
                    new Move((short) 2, (short) 2),
                    new Move((short) 3, (short) 3),
                    new Move((short) 4, (short) 4),
                    new Move((short) 5, (short) 5),
                    new Move((short) 6, (short) 6),
                    new Move((short) 7, (short) 7),
                    new Move((short) -1, (short) 1),
                    new Move((short) -2, (short) 2),
                    new Move((short) -3, (short) 3),
                    new Move((short) -4, (short) 4),
                    new Move((short) -5, (short) 5),
                    new Move((short) -6, (short) 6),
                    new Move((short) -7, (short) 7),
                    new Move((short) 1, (short) -1),
                    new Move((short) 2, (short) -2),
                    new Move((short) 3, (short) -3),
                    new Move((short) 4, (short) -4),
                    new Move((short) 5, (short) -5),
                    new Move((short) 6, (short) -6),
                    new Move((short) 7, (short) -7),
                    new Move((short) -1, (short) -1),
                    new Move((short) -2, (short) -2),
                    new Move((short) -3, (short) -3),
                    new Move((short) -4, (short) -4),
                    new Move((short) -5, (short) -5),
                    new Move((short) -6, (short) -6),
                    new Move((short) -7, (short) -7)),
            (short) 4, List.of(
                    new Move((short) 0, (short) 1),
                    new Move((short) 0, (short) 2),
                    new Move((short) 0, (short) 3),
                    new Move((short) 0, (short) 4),
                    new Move((short) 0, (short) 5),
                    new Move((short) 0, (short) 6),
                    new Move((short) 0, (short) 7),
                    new Move((short) 0, (short) -1),
                    new Move((short) 0, (short) -2),
                    new Move((short) 0, (short) -3),
                    new Move((short) 0, (short) -4),
                    new Move((short) 0, (short) -5),
                    new Move((short) 0, (short) -6),
                    new Move((short) 0, (short) -7),
                    new Move((short) 1, (short) 0),
                    new Move((short) 2, (short) 0),
                    new Move((short) 3, (short) 0),
                    new Move((short) 4, (short) 0),
                    new Move((short) 5, (short) 0),
                    new Move((short) 6, (short) 0),
                    new Move((short) 7, (short) 0),
                    new Move((short) -1, (short) 0),
                    new Move((short) -2, (short) 0),
                    new Move((short) -3, (short) 0),
                    new Move((short) -4, (short) 0),
                    new Move((short) -5, (short) 0),
                    new Move((short) -6, (short) 0),
                    new Move((short) -7, (short) 0)),
            (short) 5, List.of(
                    new Move((short) 1, (short) 1),
                    new Move((short) 2, (short) 2),
                    new Move((short) 3, (short) 3),
                    new Move((short) 4, (short) 4),
                    new Move((short) 5, (short) 5),
                    new Move((short) 6, (short) 6),
                    new Move((short) 7, (short) 7),
                    new Move((short) -1, (short) 1),
                    new Move((short) -2, (short) 2),
                    new Move((short) -3, (short) 3),
                    new Move((short) -4, (short) 4),
                    new Move((short) -5, (short) 5),
                    new Move((short) -6, (short) 6),
                    new Move((short) -7, (short) 7),
                    new Move((short) 1, (short) -1),
                    new Move((short) 2, (short) -2),
                    new Move((short) 3, (short) -3),
                    new Move((short) 4, (short) -4),
                    new Move((short) 5, (short) -5),
                    new Move((short) 6, (short) -6),
                    new Move((short) 7, (short) -7),
                    new Move((short) -1, (short) -1),
                    new Move((short) -2, (short) -2),
                    new Move((short) -3, (short) -3),
                    new Move((short) -4, (short) -4),
                    new Move((short) -5, (short) -5),
                    new Move((short) -6, (short) -6),
                    new Move((short) -7, (short) -7),
                    new Move((short) 0, (short) 1),
                    new Move((short) 0, (short) 2),
                    new Move((short) 0, (short) 3),
                    new Move((short) 0, (short) 4),
                    new Move((short) 0, (short) 5),
                    new Move((short) 0, (short) 6),
                    new Move((short) 0, (short) 7),
                    new Move((short) 0, (short) -1),
                    new Move((short) 0, (short) -2),
                    new Move((short) 0, (short) -3),
                    new Move((short) 0, (short) -4),
                    new Move((short) 0, (short) -5),
                    new Move((short) 0, (short) -6),
                    new Move((short) 0, (short) -7),
                    new Move((short) 1, (short) 0),
                    new Move((short) 2, (short) 0),
                    new Move((short) 3, (short) 0),
                    new Move((short) 4, (short) 0),
                    new Move((short) 5, (short) 0),
                    new Move((short) 6, (short) 0),
                    new Move((short) 7, (short) 0),
                    new Move((short) -1, (short) 0),
                    new Move((short) -2, (short) 0),
                    new Move((short) -3, (short) 0),
                    new Move((short) -4, (short) 0),
                    new Move((short) -5, (short) 0),
                    new Move((short) -6, (short) 0),
                    new Move((short) -7, (short) 0)),
            (short) 6, List.of(
                    new Move((short) 0, (short) 1),
                    new Move((short) 0, (short) -1),
                    new Move((short) 1, (short) 0),
                    new Move((short) -1, (short) 0),
                    new Move((short) 1, (short) 1),
                    new Move((short) -1, (short) 1),
                    new Move((short) 1, (short) -1),
                    new Move((short) -1, (short) -1))

    );
}


